/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ilicm
 */
public class AdminControl extends javax.swing.JFrame {

    Client client;
    /**
     * Creates new form AdminForm
     */
    public AdminControl(Client client) {
        initComponents();
        this.client = client;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        buttonAddCont.setVisible(true);
        buttonAddAdmin.setVisible(true);
        buttonLogout.setVisible(true);
        buttonDeleteCont.setVisible(true);
        buttonDeleteAdmin.setVisible(true);
        comboContestants.setVisible(true);
        comboAdmins.setVisible(true);
        labelContestants.setVisible(true);
        labelAdmins.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboContestants = new javax.swing.JComboBox<>();
        buttonAddCont = new javax.swing.JButton();
        buttonDeleteCont = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        comboAdmins = new javax.swing.JComboBox<>();
        buttonAddAdmin = new javax.swing.JButton();
        buttonDeleteAdmin = new javax.swing.JButton();
        labelContestants = new javax.swing.JLabel();
        labelAdmins = new javax.swing.JLabel();
        buttonLogout = new javax.swing.JButton();
        comboSet = new javax.swing.JComboBox<>();
        labelSet = new javax.swing.JLabel();
        buttonStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboContestants.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboContestants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboContestantsActionPerformed(evt);
            }
        });

        buttonAddCont.setText("DODAJ");
        buttonAddCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddContActionPerformed(evt);
            }
        });

        buttonDeleteCont.setText("OBRISI");
        buttonDeleteCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteContActionPerformed(evt);
            }
        });

        labelTitle.setText("ADMINISTRATOR");

        comboAdmins.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAdminsActionPerformed(evt);
            }
        });

        buttonAddAdmin.setText("DODAJ");
        buttonAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddAdminActionPerformed(evt);
            }
        });

        buttonDeleteAdmin.setText("OBRISI");
        buttonDeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAdminActionPerformed(evt);
            }
        });

        labelContestants.setText("Contestants:");

        labelAdmins.setText("Admins:");

        buttonLogout.setText("IZLOGUJ SE");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        comboSet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSet.setToolTipText("");
        comboSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSetActionPerformed(evt);
            }
        });

        labelSet.setText("SET:");

        buttonStart.setBackground(new java.awt.Color(204, 255, 204));
        buttonStart.setText("Start");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelContestants)
                                    .addComponent(comboContestants, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAdmins)
                                    .addComponent(comboAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(buttonAddAdmin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonDeleteAdmin))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(buttonAddCont)
                                    .addGap(113, 113, 113)
                                    .addComponent(buttonDeleteCont)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonStart))
                            .addComponent(labelSet)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(labelTitle)))
                .addGap(62, 62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonLogout)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(25, 25, 25)
                .addComponent(labelContestants)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboContestants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddCont)
                    .addComponent(buttonDeleteCont))
                .addGap(18, 18, 18)
                .addComponent(labelAdmins)
                .addGap(3, 3, 3)
                .addComponent(comboAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddAdmin)
                    .addComponent(buttonDeleteAdmin))
                .addGap(34, 34, 34)
                .addComponent(labelSet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(buttonLogout)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddContActionPerformed
        // TODO add your handling code here:
        client.addContestant();
    }//GEN-LAST:event_buttonAddContActionPerformed

    private void buttonDeleteContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteContActionPerformed
        // TODO add your handling code here:
        contestantKickedOut();
    }//GEN-LAST:event_buttonDeleteContActionPerformed

    private void buttonAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddAdminActionPerformed
        // TODO add your handling code here:
        client.addAdmin();
    }//GEN-LAST:event_buttonAddAdminActionPerformed

    private void buttonDeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAdminActionPerformed
        // TODO add your handling code here:
        adminKickedOut();
    }//GEN-LAST:event_buttonDeleteAdminActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
        client.clientLogOut();
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void comboAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAdminsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAdminsActionPerformed

    private void comboContestantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboContestantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboContestantsActionPerformed

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        // TODO add your handling code here:
        client.startSet();
    }//GEN-LAST:event_buttonStartActionPerformed

    private void comboSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSetActionPerformed

    public void contestantKickedOut()
    {
        if (comboSet.getSelectedIndex() != -1)
        {
            String message = "Contestant kicked out:" + comboContestants.getSelectedItem().toString();
            System.out.println(message);
            client.setMessage(message);
        }
    }
    
    public void adminKickedOut()
    {    
        if (comboSet.getSelectedIndex() != -1)
        {
            String message = "Admin kicked out:" + comboAdmins.getSelectedItem().toString();
            client.setMessage(message);
        }
    }
    
    public void updateContestants(String [] names) 
    {
        comboContestants.removeAllItems();
        for (String name : names) 
        {
            comboContestants.addItem(name);
        }
    }
    
    public void updateAdmins(String [] names) 
    {
        comboAdmins.removeAllItems();
        for (String name : names) 
        {
            comboAdmins.addItem(name);            
        }
    }

    public void updateAdmUsername(String username)
    {
        this.labelTitle.setText(username);
    }
    
    public void startSet()
    {
        if (comboSet.getSelectedIndex() != -1)
        {
            String message = "Activate set:" + comboSet.getSelectedItem().toString();
            client.setMessage(message);
        }
    }
    /**
     * @param args the command line arguments
     */
    public void tryAgain(String errorMessage) {
        JOptionPane.showMessageDialog(null, errorMessage);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddAdmin;
    private javax.swing.JButton buttonAddCont;
    private javax.swing.JButton buttonDeleteAdmin;
    private javax.swing.JButton buttonDeleteCont;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonStart;
    private javax.swing.JComboBox<String> comboAdmins;
    private javax.swing.JComboBox<String> comboContestants;
    private javax.swing.JComboBox<String> comboSet;
    private javax.swing.JLabel labelAdmins;
    private javax.swing.JLabel labelContestants;
    private javax.swing.JLabel labelSet;
    private javax.swing.JLabel labelTitle;
    // End of variables declaration//GEN-END:variables
}
